import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

import { createOperationScope } from '../../providers/operation-scope.ts'
import {
  createProviderTransport,
  type ProviderRequestOptions,
  type ProviderTransport,
} from '../../providers/transport.ts'
import { createImageStore, type ImageStore } from '../lib/image-store.ts'
import type { ProjectScreenshotViewport } from '../lib/project-screenshot.ts'
import type { ProjectRepository } from '../lib/project-store.ts'
import { createScreenshotTool } from './screenshot.ts'

type FetchMock = typeof globalThis.fetch

let imageStore: ImageStore
const repository: Pick<ProjectRepository, 'appendVisionMessage'> = {
  appendVisionMessage: vi.fn<ProjectRepository['appendVisionMessage']>(
    async () => [],
  ),
}

beforeEach(() => {
  imageStore = createImageStore()
  vi.mocked(repository.appendVisionMessage).mockClear()
})

afterEach(() => {
  vi.doUnmock('firecrawl')
  vi.doUnmock('../lib/image-ocr.ts')
  vi.unstubAllEnvs()
  vi.unstubAllGlobals()
  vi.resetModules()
  vi.restoreAllMocks()
})

describe('image-store', () => {
  it('stores images with media-type specific extensions', () => {
    const jpegId = imageStore.saveImage(
      Buffer.from([0xff, 0xd8, 0xff, 0x00]),
      'image/jpeg',
    )
    const svgId = imageStore.saveImage(Buffer.from('<svg />'), 'image/svg+xml')
    const webpId = imageStore.saveImage(
      Buffer.from('RIFFxxxxWEBP'),
      'image/webp',
    )
    const gifId = imageStore.saveImage(Buffer.from('GIF89a'), 'image/gif')
    const fallbackId = imageStore.saveImage(
      Buffer.from('raw'),
      'application/octet-stream',
    )

    expect(imageStore.getImage(jpegId)).toMatchObject({ extension: 'jpg' })
    expect(imageStore.getImage(svgId)).toMatchObject({ extension: 'svg' })
    expect(imageStore.getImage(webpId)).toMatchObject({ extension: 'webp' })
    expect(imageStore.getImage(gifId)).toMatchObject({ extension: 'gif' })
    expect(imageStore.getImage(fallbackId)).toMatchObject({ extension: 'png' })
  })
})

describe('createGenerateImageTool', () => {
  it('returns a clear failure when OpenRouter is not configured', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool()
    const tool = createGenerateImageTool('http://server.test', imageStore)

    const result = await tool.execute?.(
      {
        action: 'Create a hero image',
        prompt: 'A cinematic product render on a clean desk',
      },
      undefined as never,
    )

    expect(result).toMatchObject({
      imagesGenerated: 0,
      ok: false,
      reason: expect.stringContaining('OPENROUTER_API_KEY is not set'),
      url: null,
    })
  })

  it('saves successful image responses and detects image media types', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    const fetch = vi.fn<FetchMock>(async () =>
      jsonResponse({
        data: [
          {
            b64_json: Buffer.from([0xff, 0xd8, 0xff, 0x00]).toString('base64'),
          },
        ],
        usage: { cost: 0.031 },
      }),
    )
    vi.stubGlobal('fetch', fetch)

    const tool = createGenerateImageTool('http://server.test', imageStore)
    const result = await tool.execute?.(
      {
        action: 'Create a square product image',
        aspectRatio: '1:1',
        prompt: 'A detailed product render in soft studio light',
      },
      undefined as never,
    )
    if (!result || !('url' in result)) {
      throw new Error('Expected generate_image result with a URL')
    }

    expect(result).toMatchObject({
      cost: 0.031,
      imagesGenerated: 1,
      ok: true,
      url: expect.stringMatching(
        /^http:\/\/server\.test\/images\/img-[a-f0-9-]+\.jpg$/,
      ),
    })
    const id = String(result.url).match(/images\/(img-[a-f0-9-]+)\.jpg/)?.[1]
    expect(id ? imageStore.getImage(id) : undefined).toMatchObject({
      extension: 'jpg',
      mediaType: 'image/jpeg',
    })
    expect(JSON.parse(fetch.mock.calls[0]![1]!.body as string)).toMatchObject({
      aspect_ratio: '1:1',
      model: 'bytedance-seed/seedream-4.5',
    })
  })

  it('persists generated bytes before returning a successful tool result', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    vi.stubGlobal(
      'fetch',
      vi.fn<FetchMock>(async () =>
        jsonResponse({
          data: [
            {
              b64_json: Buffer.from([0xff, 0xd8, 0xff, 0x00]).toString(
                'base64',
              ),
            },
          ],
        }),
      ),
    )
    const persisted: string[] = []
    const tool = createGenerateImageTool(
      'http://server.test',
      imageStore,
      undefined,
      (id, extension) => {
        expect(imageStore.getImage(id)?.buffer).toEqual(
          Buffer.from([0xff, 0xd8, 0xff, 0x00]),
        )
        persisted.push(`${id}${extension}`)
        return `/api/projects/project/images/${id}${extension}`
      },
    )

    await expect(
      tool.execute?.(
        {
          action: 'Create a durable image',
          prompt: 'A durable studio product image in warm light',
        },
        undefined as never,
      ),
    ).resolves.toMatchObject({ imagesGenerated: 1, ok: true })
    expect(persisted).toEqual([expect.stringMatching(/^img-[a-f0-9-]+\.jpg$/)])
  })

  it('reports persistence failure instead of publishing success', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    vi.stubGlobal(
      'fetch',
      vi.fn<FetchMock>(async () =>
        jsonResponse({
          data: [{ b64_json: Buffer.from('GIF89a').toString('base64') }],
          usage: { cost: 0.027 },
        }),
      ),
    )
    const operations = createOperationScope()
    const tool = createGenerateImageTool(
      'http://server.test',
      imageStore,
      undefined,
      () => null,
      { operations },
    )

    await expect(
      tool.execute?.(
        {
          action: 'Create an image',
          prompt: 'A generated image that cannot reach durable storage',
        },
        undefined as never,
      ),
    ).resolves.toMatchObject({
      imagesGenerated: 0,
      ok: false,
      reason: expect.stringContaining('could not be persisted'),
      url: null,
    })
    await expect(operations.drain()).resolves.toEqual({ ok: true })
    expect(operations.getUsageReports()).toEqual([
      expect.objectContaining({
        amount: 0.027,
        category: 'image',
        count: 1,
      }),
    ])
  })

  it('detects generated image extensions from bytes or declared media types', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    const fetch = vi
      .fn<FetchMock>()
      .mockResolvedValueOnce(
        jsonResponse({
          data: [{ b64_json: Buffer.from('GIF89a').toString('base64') }],
        }),
      )
      .mockResolvedValueOnce(
        jsonResponse({
          data: [{ b64_json: Buffer.from('RIFFxxxxWEBP').toString('base64') }],
        }),
      )
      .mockResolvedValueOnce(
        jsonResponse({
          data: [
            {
              b64_json: Buffer.from([1, 2]).toString('base64'),
              media_type: 'image/gif',
            },
          ],
        }),
      )
      .mockResolvedValueOnce(
        jsonResponse({
          data: [{ b64_json: Buffer.from([1, 2, 3, 4]).toString('base64') }],
        }),
      )
    vi.stubGlobal('fetch', fetch)

    const tool = createGenerateImageTool('http://server.test', imageStore)
    const urls: string[] = []
    for (const prompt of [
      'gif image prompt',
      'webp image prompt',
      'declared gif prompt',
      'fallback png prompt',
    ]) {
      const result = await tool.execute?.(
        { action: 'Create image', prompt },
        undefined as never,
      )
      if (!result || !('url' in result)) {
        throw new Error('Expected generate_image result with a URL')
      }
      urls.push(String(result.url))
    }

    expect(urls).toEqual([
      expect.stringMatching(/\.gif$/),
      expect.stringMatching(/\.webp$/),
      expect.stringMatching(/\.gif$/),
      expect.stringMatching(/\.png$/),
    ])
  })

  it('handles image API failures and empty responses', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    const tool = createGenerateImageTool('http://server.test', imageStore)

    vi.stubGlobal(
      'fetch',
      vi.fn<FetchMock>(async () => new Response('bad', { status: 502 })),
    )
    await expect(
      tool.execute?.(
        {
          action: 'Try image generation',
          prompt: 'A detailed product render in soft studio light',
        },
        undefined as never,
      ),
    ).resolves.toMatchObject({
      ok: false,
      reason: expect.stringContaining('HTTP 502'),
    })

    vi.stubGlobal(
      'fetch',
      vi.fn<FetchMock>(async () => jsonResponse({ data: [] })),
    )
    await expect(
      tool.execute?.(
        {
          action: 'Try image generation again',
          prompt: 'A detailed product render in soft studio light',
        },
        undefined as never,
      ),
    ).resolves.toMatchObject({
      ok: false,
      reason: 'OpenRouter returned no image data.',
    })
  })

  it('does not retry paid image generation after a provider failure', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    const fetch = vi
      .fn<FetchMock>()
      .mockResolvedValueOnce(new Response('down', { status: 503 }))
      .mockResolvedValueOnce(
        jsonResponse({
          data: [
            {
              b64_json: Buffer.from([0xff, 0xd8, 0xff, 0x00]).toString(
                'base64',
              ),
            },
          ],
          usage: { cost: 0.031 },
        }),
      )
    vi.stubGlobal('fetch', fetch)

    const tool = createGenerateImageTool('http://server.test', imageStore)
    const result = await tool.execute?.(
      {
        action: 'Create hero image',
        prompt: 'A cinematic product render on a clean desk',
      },
      undefined as never,
    )

    expect(result).toMatchObject({ cost: 0, ok: false })
    expect(fetch).toHaveBeenCalledTimes(1)
  })

  it('surfaces an operation deadline when the image API hangs', async () => {
    const { createGenerateImageTool } = await loadGenerateImageTool({
      OPENROUTER_API_KEY: 'openrouter-key',
    })
    // fetch that never resolves until aborted (honors the abort signal).
    const fetch = vi.fn<FetchMock>(
      (_url, init) =>
        new Promise<Response>((_resolve, reject) => {
          init?.signal?.addEventListener(
            'abort',
            () => {
              const err = new Error('The operation was aborted')
              err.name = 'AbortError'
              reject(err)
            },
            { once: true },
          )
        }),
    )
    vi.stubGlobal('fetch', fetch)

    const operations = createOperationScope({ operationTimeoutMs: 5 })
    const pending = createGenerateImageTool(
      'http://server.test',
      imageStore,
      undefined,
      undefined,
      { operations, transport: createProviderTransport({ fetch }) },
    ).execute?.(
      {
        action: 'Create hero image',
        prompt: 'A cinematic product render on a clean desk',
      },
      undefined as never,
    )
    await expect(pending).rejects.toThrow(/deadline|timed out/i)
    await expect(operations.drain()).resolves.toEqual({ ok: true })
  })
})

describe('createScrapeTool', () => {
  it('returns a clear failure when Firecrawl is not configured', async () => {
    const { createScrapeTool } = await loadScrapeTool()
    const tool = createScrapeTool({ repository })

    const result = await tool.execute?.(
      {
        action: 'Scrape brand identity',
        url: 'https://example.test',
      },
      undefined as never,
    )

    expect(result).toMatchObject({
      branding: null,
      imageCount: 0,
      imageOcr: { imagesAnalyzed: 0, ok: false },
      ok: false,
      reason: expect.stringContaining('FIRECRAWL_API_KEY is not set'),
    })
  })

  it('falls back to OCRing unique images when the scrape returns no screenshot', async () => {
    const scrape = vi.fn<() => Promise<Record<string, unknown>>>(async () => ({
      branding: { colorScheme: 'dark', logo: '/logo.png' },
      images: [
        '/hero.png',
        'data:image/png;base64,abc',
        '/hero.png',
        'https://lh3.googleusercontent.com/Twq8KO0WJT02OhJP2VjxhLmOJbeAZgiU4ZSCi2o6',
      ],
      links: ['https://example.test/pricing'],
      markdown:
        '![Logo](/logo.png)\n![CDN](https://cdn.example.test/card.webp)',
      metadata: {
        creditsUsed: 2,
        image: 'https://example.test/social.jpg',
        sourceURL: 'https://example.test/home',
        title: 'Example',
      },
    }))
    const ocrImages = vi.fn<
      (images: string[]) => Promise<{
        imagesAnalyzed: number
        ok: boolean
        text: string
        usage: null
      }>
    >(async (images) => ({
      imagesAnalyzed: images.length,
      ok: true,
      text: 'Image 1\nLogo',
      usage: null,
    }))
    const { createScrapeTool } = await loadScrapeTool({
      FIRECRAWL_API_KEY: 'firecrawl-key',
      ocrImages,
      scrape,
    })

    const tool = createScrapeTool({ repository })
    const result = await tool.execute?.(
      {
        action: 'Scrape brand identity',
        excludeTags: ['nav'],
        includeTags: ['main'],
        url: 'https://example.test/path',
        waitFor: 250,
      },
      undefined as never,
    )

    expect(scrape).toHaveBeenCalledWith('https://example.test/path', {
      excludeTags: ['nav'],
      formats: [
        { fullPage: true, type: 'screenshot' },
        'markdown',
        'links',
        'images',
        'branding',
        {
          prompt: 'Describe each image',
          schema: expect.objectContaining({ type: 'object' }),
          type: 'json',
        },
      ],
      includeTags: ['main'],
      maxAge: 172_800_000,
      onlyMainContent: true,
      parsers: ['pdf'],
      timeout: 30_000,
      waitFor: 250,
    })
    expect(ocrImages).toHaveBeenCalledWith(
      [
        'https://example.test/hero.png',
        'https://lh3.googleusercontent.com/Twq8KO0WJT02OhJP2VjxhLmOJbeAZgiU4ZSCi2o6',
        'https://example.test/logo.png',
        'https://cdn.example.test/card.webp',
        'https://example.test/social.jpg',
      ],
      undefined,
      'bytedance-seed/seed-2.0-mini',
      undefined,
      expect.objectContaining({ source: 'scrape' }),
    )
    expect(result).toMatchObject({
      branding: { colorScheme: 'dark' },
      charCount: expect.any(Number),
      creditsUsed: 2,
      imageCount: 5,
      linkCount: 1,
      ok: true,
      title: 'Example',
      url: 'https://example.test/home',
    })
  })

  it('OCRs the full-page screenshot with the layout prompt when present', async () => {
    const scrape = vi.fn<() => Promise<Record<string, unknown>>>(async () => ({
      images: ['/hero.png'],
      json: {
        images: [
          {
            description: 'Dark hero banner with orange CTA',
            height: 600,
            url: 'https://example.test/hero.png',
            width: 1200,
          },
          'not-an-object',
        ],
      },
      links: [],
      markdown: '',
      metadata: { creditsUsed: 3, title: 'Example' },
      screenshot: 'https://storage.example.test/full-page.png?sig=abc',
    }))
    const ocrImages = vi.fn<
      (
        images: string[],
        prompt?: string,
      ) => Promise<{
        imagesAnalyzed: number
        ok: boolean
        text: string
        usage: null
      }>
    >(async (images) => ({
      imagesAnalyzed: images.length,
      ok: true,
      text: 'Layout: hero, features, footer',
      usage: null,
    }))
    const { createScrapeTool } = await loadScrapeTool({
      FIRECRAWL_API_KEY: 'firecrawl-key',
      ocrImages,
      scrape,
    })

    const tool = createScrapeTool({ repository })
    const result = await tool.execute?.(
      { action: 'Scrape brand identity', url: 'https://example.test' },
      undefined as never,
    )

    expect(ocrImages).toHaveBeenCalledWith(
      ['https://storage.example.test/full-page.png?sig=abc'],
      expect.stringContaining('full-page screenshot'),
      'bytedance-seed/seed-2.0-mini',
      undefined,
      expect.objectContaining({ source: 'scrape' }),
    )
    expect(result).toMatchObject({
      imageDescriptions: [
        {
          description: 'Dark hero banner with orange CTA',
          height: 600,
          url: 'https://example.test/hero.png',
          width: 1200,
        },
      ],
      imageOcr: {
        imagesAnalyzed: 1,
        ok: true,
        text: 'Layout: hero, features, footer',
      },
      ok: true,
      screenshot: 'https://storage.example.test/full-page.png?sig=abc',
    })
  })

  it('logs scrape OCR to vision-messages.json when projectId/turnId are set', async () => {
    const scrape = vi.fn<() => Promise<Record<string, unknown>>>(async () => ({
      images: ['/hero.png'],
      links: [],
      markdown: '',
      metadata: { title: 'X' },
    }))
    const ocrImages = vi.fn<
      (images: string[]) => Promise<{
        cost: number
        imagesAnalyzed: number
        ok: boolean
        text: string
        usage: null
      }>
    >(async (images) => ({
      cost: 0.002,
      imagesAnalyzed: images.length,
      ok: true,
      text: 'a hero shot',
      usage: null,
    }))
    const appendVisionMessage =
      vi.fn<(id: string, entry: unknown) => Promise<void>>()
    const { createScrapeTool } = await loadScrapeTool({
      appendVisionMessage,
      FIRECRAWL_API_KEY: 'firecrawl-key',
      ocrImages,
      scrape,
    })

    const tool = createScrapeTool({
      projectId: 'proj-1',
      repository: { appendVisionMessage: appendVisionMessage as never },
      turnId: 'turn-1',
    })
    await tool.execute?.(
      { action: 'Scrape brand', url: 'https://example.test' },
      undefined as never,
    )

    expect(appendVisionMessage).toHaveBeenCalledWith(
      'proj-1',
      expect.objectContaining({
        imagesAnalyzed: 1,
        model: 'bytedance-seed/seed-2.0-mini',
        ok: true,
        source: 'scrape',
        text: 'a hero shot',
        turnId: 'turn-1',
      }),
    )
  })

  it('does not log scrape OCR when projectId/turnId are absent', async () => {
    const scrape = vi.fn<() => Promise<Record<string, unknown>>>(async () => ({
      images: ['/hero.png'],
      links: [],
      markdown: '',
      metadata: {},
    }))
    const ocrImages = vi.fn<
      () => Promise<{
        imagesAnalyzed: number
        ok: boolean
        text: string
        usage: null
      }>
    >(async () => ({
      imagesAnalyzed: 1,
      ok: true,
      text: 'x',
      usage: null,
    }))
    const appendVisionMessage =
      vi.fn<(id: string, entry: unknown) => Promise<void>>()
    const { createScrapeTool } = await loadScrapeTool({
      appendVisionMessage,
      FIRECRAWL_API_KEY: 'firecrawl-key',
      ocrImages,
      scrape,
    })

    await createScrapeTool({ repository }).execute?.(
      { action: 'Scrape brand', url: 'https://example.test' },
      undefined as never,
    )

    expect(appendVisionMessage).not.toHaveBeenCalled()
  })
})

describe('createScreenshotTool', () => {
  it('reports unavailable and failed capture paths', async () => {
    const unavailable = createScreenshotTool()
    await expect(
      unavailable.execute?.(
        {
          action: 'Check desktop hero layout',
          selector: '#hero',
        },
        undefined as never,
      ),
    ).resolves.toMatchObject({
      captures: [],
      ok: false,
      reason: 'Screenshot capture is unavailable in this runtime.',
    })

    const failing = createScreenshotTool(async () => {
      throw new Error('browser closed')
    })
    await expect(
      failing.execute?.(
        {
          action: 'Check mobile hero layout',
          selector: '#hero',
        },
        undefined as never,
      ),
    ).resolves.toMatchObject({
      captures: [],
      ok: false,
      reason: 'browser closed',
    })
  })

  it('captures three viewports and OCRs all images in one call', async () => {
    vi.resetModules()
    const ocrImageInputs = vi.fn<
      (inputs: unknown[]) => Promise<{
        cost: number
        imagesAnalyzed: number
        ok: boolean
        text: string
        usage: null
      }>
    >(async () => ({
      cost: 0.004,
      imagesAnalyzed: 3,
      ok: true,
      text: 'Hero headline visible across viewports',
      usage: null,
    }))
    vi.doMock('../lib/image-ocr.ts', () => ({ ocrImageInputs }))
    const { createScreenshotTool: loadTool } = await import('./screenshot.ts')
    const captureProjectSelector = vi.fn<
      (selector: string) => Promise<{
        captures: {
          dataUrl: string
          elementMap: string
          height: number
          imageUrl: string
          mediaType: 'image/png'
          viewport: ProjectScreenshotViewport
          width: number
        }[]
        selector: string
      }>
    >(async (selector) => ({
      captures: [
        {
          dataUrl: 'data:image/jpeg;base64,/9j/AAA=',
          elementMap: '',
          height: 422,
          imageUrl: '/api/projects/p/screenshots/001-mobile.jpg',
          mediaType: 'image/png',
          viewport: 'mobile',
          width: 195,
        },
        {
          dataUrl: 'data:image/jpeg;base64,/9j/BBB=',
          elementMap: '',
          height: 512,
          imageUrl: '/api/projects/p/screenshots/002-tablet.jpg',
          mediaType: 'image/png',
          viewport: 'tablet',
          width: 384,
        },
        {
          dataUrl: 'data:image/jpeg;base64,/9j/CCC=',
          elementMap: '',
          height: 450,
          imageUrl: '/api/projects/p/screenshots/003-desktop.jpg',
          mediaType: 'image/png',
          viewport: 'desktop',
          width: 720,
        },
      ] as {
        dataUrl: string
        elementMap: string
        height: number
        imageUrl: string
        mediaType: 'image/png'
        viewport: ProjectScreenshotViewport
        width: number
      }[],
      selector,
    }))

    const tool = loadTool(captureProjectSelector)
    const result = await tool.execute?.(
      {
        action: 'Check hero spacing and CTA contrast',
        selector: '#hero',
      },
      undefined as never,
    )

    expect(captureProjectSelector).toHaveBeenCalledWith('#hero', undefined)
    expect(ocrImageInputs).toHaveBeenCalledTimes(1)
    expect((ocrImageInputs.mock.calls[0] as unknown[])?.[4]).toMatchObject({
      signal: undefined,
    })
    expect(ocrImageInputs.mock.calls[0]?.[0]).toHaveLength(3)
    expect(result).toMatchObject({
      captures: expect.arrayContaining([
        expect.objectContaining({ viewport: 'mobile' }),
        expect.objectContaining({ viewport: 'tablet' }),
        expect.objectContaining({ viewport: 'desktop' }),
      ]),
      imageOcr: { cost: 0.004, imagesAnalyzed: 3, ok: true },
      ok: true,
      selector: '#hero',
      text: 'Hero headline visible across viewports',
    })
    expect(JSON.stringify(result)).not.toContain('data:image/jpeg')
  })
})

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    headers: { 'content-type': 'application/json' },
    status,
  })
}

async function loadGenerateImageTool(env: Record<string, string> = {}) {
  vi.resetModules()
  vi.stubEnv('OPENROUTER_API_KEY', 'test-openrouter-key')
  vi.stubEnv('OPENROUTER_API_KEY', '')
  for (const [name, value] of Object.entries(env)) vi.stubEnv(name, value)
  return import('./generate-image.ts')
}

async function loadScrapeTool({
  appendVisionMessage = vi.fn<(id: string, entry: unknown) => Promise<void>>(),
  FIRECRAWL_API_KEY,
  ocrImages = vi.fn<() => Promise<unknown>>(),
  scrape = vi.fn<() => Promise<unknown>>(),
}: {
  appendVisionMessage?: ReturnType<typeof vi.fn>
  FIRECRAWL_API_KEY?: string
  ocrImages?: ReturnType<typeof vi.fn>
  scrape?: ReturnType<typeof vi.fn>
} = {}) {
  vi.resetModules()
  vi.stubEnv('OPENROUTER_API_KEY', 'test-openrouter-key')
  vi.stubEnv('FIRECRAWL_API_KEY', '')
  if (FIRECRAWL_API_KEY) vi.stubEnv('FIRECRAWL_API_KEY', FIRECRAWL_API_KEY)
  vi.doMock('../lib/image-ocr.ts', () => ({ ocrImages }))
  vi.doMock('../lib/project-store.ts', () => ({ appendVisionMessage }))
  const module = await import('./scrape.ts')
  const scrapeCall = scrape as unknown as (
    url: string,
    options: Record<string, unknown>,
  ) => Promise<unknown>
  const transport: ProviderTransport = {
    async bytes() {
      throw new Error('Unexpected byte request.')
    },
    async json<T>(options: ProviderRequestOptions) {
      const request = JSON.parse(String(options.init?.body)) as {
        [key: string]: unknown
        url: string
      }
      const { url, ...scrapeOptions } = request
      const data = await scrapeCall(url, scrapeOptions)
      return {
        headers: new Headers(),
        ok: true as const,
        status: 200,
        value: { data, success: true } as T,
      }
    },
    async text() {
      throw new Error('Unexpected text request.')
    },
  }
  return {
    ...module,
    createScrapeTool(options: Parameters<typeof module.createScrapeTool>[0]) {
      return module.createScrapeTool({ ...options, transport })
    },
  }
}
