/**
 * Module-level in-memory image store. Images generated by the `generate_image`
 * tool are kept here and served via the `GET /images/:id` route so the agent
 * can reference them by a short URL instead of carrying huge base64 payloads
 * in its own context.
 *
 * Process-scoped: images survive across requests within a running server, and
 * are cleared on restart.
 */

export interface StoredImage {
  buffer: Buffer
  createdAt: number
  extension: string
  mediaType: string
}

const images = new Map<string, StoredImage>()
let counter = 0

/** Look up a stored image by id. */
export function getImage(id: string): StoredImage | undefined {
  return images.get(id)
}

/** Store raw image bytes and return a stable id (e.g. `img-1`). */
export function saveImage(buffer: Buffer, mediaType: string): string {
  counter += 1
  const id = `img-${counter}`
  images.set(id, {
    buffer,
    createdAt: Date.now(),
    extension: extensionFor(mediaType),
    mediaType,
  })
  return id
}

function extensionFor(mediaType: string): string {
  if (mediaType === 'image/svg+xml') return 'svg'
  if (mediaType === 'image/jpeg') return 'jpg'
  if (mediaType === 'image/webp') return 'webp'
  if (mediaType === 'image/gif') return 'gif'
  return 'png'
}
