import { LANDING_MODEL_OPTIONS } from '@workspace/prompt-panel'
import { Button } from '@workspace/ui/components/button'
import { cn } from '@workspace/ui/lib/utils'
import { ArrowRight, FileCode2, Plus, Trash2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'

import {
  type ProjectMeta,
  createProject,
  deleteProject,
  expandProjectImageUrls,
  getProject,
  listProjects,
} from '../lib/projects-api'

/** Creates a draft project on mount and redirects to its editor route. */
export function NewProjectPage() {
  const [createdId, setCreatedId] = useState<null | string>(null)
  const [error, setError] = useState<null | string>(null)
  const navigate = useNavigate()

  useEffect(() => {
    let cancelled = false
    void createProject({ model: LANDING_MODEL_OPTIONS[0]!.id })
      .then((project) => {
        if (!cancelled) setCreatedId(project.id)
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(
            err instanceof Error ? err.message : 'Failed to create project',
          )
        }
      })
    return () => {
      cancelled = true
    }
  }, [])

  if (error) {
    return (
      <main className="grid min-h-svh place-items-center bg-background p-6 text-center">
        <div>
          <p className="text-sm text-destructive">{error}</p>
          <Button
            className="mt-4"
            onClick={() => navigate('/')}
            type="button"
            variant="outline"
          >
            Back to projects
          </Button>
        </div>
      </main>
    )
  }

  if (!createdId) {
    return (
      <main className="grid min-h-svh place-items-center bg-background text-sm text-muted-foreground">
        Creating project…
      </main>
    )
  }

  return <Navigate replace to={`/projects/${createdId}`} />
}

export function ProjectsPage() {
  const [projects, setProjects] = useState<ProjectMeta[]>([])
  const [error, setError] = useState<null | string>(null)
  const [loading, setLoading] = useState(true)
  const navigate = useNavigate()

  const refresh = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      setProjects(await listProjects())
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load projects')
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh])

  const handleDelete = useCallback(async (id: string) => {
    if (!window.confirm('Delete this project? This cannot be undone.')) return
    try {
      await deleteProject(id)
      setProjects((prev) => prev.filter((project) => project.id !== id))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete project')
    }
  }, [])

  return (
    <main className="min-h-svh bg-background text-foreground">
      <div className="mx-auto w-full max-w-5xl px-6 py-10">
        <header className="mb-8 flex items-end justify-between gap-4 border-b border-border pb-5">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Projects</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Landing pages generated by the agent. Each is a single HTML file.
            </p>
          </div>
          <Button onClick={() => navigate('/projects/new')} type="button">
            <Plus data-icon="inline-start" />
            New project
          </Button>
        </header>

        {error ? (
          <p className="border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive">
            {error}
          </p>
        ) : null}

        {loading ? (
          <p className="text-sm text-muted-foreground">Loading projects…</p>
        ) : projects.length === 0 ? (
          <EmptyState onCreate={() => navigate('/projects/new')} />
        ) : (
          <ul className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {projects.map((project) => (
              <ProjectCard
                key={project.id}
                onDelete={handleDelete}
                onOpen={(id) => navigate(`/projects/${id}`)}
                project={project}
              />
            ))}
          </ul>
        )}
      </div>
    </main>
  )
}

function EmptyState({ onCreate }: { onCreate: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center border border-dashed border-border px-6 py-16 text-center">
      <span className="mb-4 flex size-12 items-center justify-center border border-border bg-card text-muted-foreground">
        <FileCode2 className="size-5" />
      </span>
      <h2 className="text-base font-medium">No projects yet</h2>
      <p className="mt-1 max-w-sm text-sm text-muted-foreground">
        Create your first landing page. Describe a site or paste a reference URL
        and the agent builds a single-file HTML page.
      </p>
      <Button className="mt-5" onClick={onCreate} type="button">
        <Plus data-icon="inline-start" />
        New project
      </Button>
    </div>
  )
}

function formatRelative(iso: string): string {
  const then = new Date(iso).getTime()
  if (Number.isNaN(then)) return 'unknown'
  const diffMs = Date.now() - then
  const sec = Math.round(diffMs / 1000)
  if (sec < 45) return 'just now'
  const min = Math.round(sec / 60)
  if (min < 60) return `${min}m ago`
  const hr = Math.round(min / 60)
  if (hr < 24) return `${hr}h ago`
  const day = Math.round(hr / 24)
  if (day < 7) return `${day}d ago`
  return new Date(iso).toLocaleDateString(undefined, {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

function ProjectCard({
  onDelete,
  onOpen,
  project,
}: {
  onDelete: (id: string) => void
  onOpen: (id: string) => void
  project: ProjectMeta
}) {
  const title = project.title || 'Untitled'

  return (
    <li className="group relative">
      <article
        className={cn(
          'relative overflow-hidden border border-border bg-card',
          'transition-colors group-hover:border-foreground/30 group-hover:bg-muted/50',
        )}
      >
        <ProjectCardPreview project={project} />
        <div className="flex items-end gap-3 p-4">
          <span className="min-w-0 flex-1">
            <span className="block truncate text-sm font-medium text-foreground">
              {title}
            </span>
            <span className="mt-0.5 block text-xs text-muted-foreground">
              Updated {formatRelative(project.updatedAt)}
            </span>
          </span>
          <ArrowRight className="size-4 text-muted-foreground transition-colors group-hover:text-foreground" />
        </div>
        <button
          aria-label={`Open ${title}`}
          className={cn(
            'absolute inset-0 z-10',
            'focus-visible:border-ring focus-visible:ring-2 focus-visible:ring-ring/40 focus-visible:outline-none',
          )}
          onClick={() => onOpen(project.id)}
          type="button"
        >
          <span className="sr-only">Open {title}</span>
        </button>
      </article>
      <button
        aria-label={`Delete ${title}`}
        className={cn(
          'absolute top-2 right-2 z-20 inline-flex size-7 items-center justify-center',
          'border border-border bg-background text-muted-foreground',
          'opacity-0 transition-opacity hover:bg-destructive/10 hover:text-destructive',
          'group-hover:opacity-100 focus-visible:opacity-100',
        )}
        onClick={(event) => {
          event.stopPropagation()
          onDelete(project.id)
        }}
        title="Delete project"
        type="button"
      >
        <Trash2 className="size-3.5" />
      </button>
    </li>
  )
}

function ProjectCardPreview({ project }: { project: ProjectMeta }) {
  const [failed, setFailed] = useState(false)
  const [previewHtml, setPreviewHtml] = useState<null | string>(null)
  const title = project.title || 'Untitled'

  useEffect(() => {
    let cancelled = false

    setFailed(false)
    setPreviewHtml(null)
    void getProject(project.id)
      .then((fullProject) => {
        if (!cancelled) {
          setPreviewHtml(expandProjectImageUrls(fullProject.indexHtml))
        }
      })
      .catch(() => {
        if (!cancelled) setFailed(true)
      })

    return () => {
      cancelled = true
    }
  }, [project.id, project.updatedAt])

  return (
    <div className="relative h-40 overflow-hidden border-b border-border bg-background">
      {previewHtml ? (
        <iframe
          className="pointer-events-none size-[334%] origin-top-left scale-[0.3] border-0 bg-background"
          loading="lazy"
          sandbox=""
          srcDoc={previewHtml}
          tabIndex={-1}
          title={`Preview of ${title}`}
        />
      ) : (
        <div className="flex h-full flex-col items-center justify-center gap-2 text-muted-foreground">
          <FileCode2 className="size-5" />
          <span className="text-xs">
            {failed ? 'Preview unavailable' : 'Loading preview…'}
          </span>
        </div>
      )}
    </div>
  )
}
